apiVersion: v1
kind: Service
metadata:
  name: kcnaprep-s
spec:
  type: ClusterIP # This service type is used for internal communication within the cluster
  selector:
    app: kcnaprep-s
  ports:
  - name: http
    port: 80 # This is the port exposed by the service
    targetPort: 3000 # This is the port on the container
