apiVersion: v1
kind: Service
metadata:
  name: kcnaprep-d
spec:
  type: NodePort
  selector:
    app: kcnaprep-d
  ports:
  - port: 3000 # This is the port exposed by the service
    targetPort: 3000 # This is the port on the container
    nodePort: 30001 # This is the port on the node that will be exposed
