apiVersion: v1
kind: Service
metadata:
  name: kcnaprep-d
spec:
  selector:
    app: kcnaprep-d
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  externalIPs:
  - 1.2.3.4 # Replace with your actual external IP of Worker Node