apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  pgpassword: VmVyeVNlY3VyZVBhc3N3b3Jk  # Base64 encoded value of 'VerySecurePassword'
---
# Update the ConfigMap to remove the password
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cm
  labels:
    app: postgres
data:
  POSTGRES_DB: pgdb
  POSTGRES_USER: pguser