apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probe
  template:
    metadata:
      labels:
        app: probe
    spec:
      containers:
      - name: probe
        image: k8s.gcr.io/liveness
        args:
        - /server
        - --port=8080
        - --health-path=/healthz
        ports:
        - containerPort: 8080
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: probe-service
spec:
  type: NodePort
  selector:
    app: probe-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30036  # You can change this if needed
