---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscale-hpa
  template:
    metadata:
      labels:
        app: autoscale-hpa
    spec:
      containers:
      - name: autoscale-hpa
        image: k8s.gcr.io/hpa-example
        resources:
          requests:
            cpu: "25m" # This is a very low request to demonstrate scaling
          limits:
            cpu: "50m" # This is a very low limit to demonstrate scaling
        ports:
        - containerPort: 80
