apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-vpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscale-vpa
  template:
    metadata:
      labels:
        app: autoscale-vpa
    spec:
      containers:
      - name: stress-ng
        image: polinux/stress
        command: ["stress"]
        args: ["--cpu", "1", "--timeout", "300s"]
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"