apiVersion: v1
kind: Service
metadata:
  name: mc
spec:
  type: NodePort
  selector:
    app: mc
  ports:
  - port: 8080 # This is the port exposed by the service
    targetPort: 80 # This is the port on the container
    nodePort: 30002 # This is the port on the node that will be exposed